package main

// docs_content.odin — the documentation shown by `gjallarhorn docs`. One Topic per
// framework area, kept terse and API-first. Body-line conventions (see docs.odin):
//   "# heading"   section header      "  code / api"   verbatim code line
//   ""            blank spacer         "prose…"         word-wrapped paragraph

doc_topics :: proc() -> []Topic {
	@(static) topics := []Topic {
		{
			"Overview",
			"a from-scratch web framework in Odin, no dependencies",
			{
				"Gjallarhorn is a small, honest HTTP/1.1 framework: a hand-rolled server, a router, an onion of middleware (\"runes\"), signed-cookie sessions with CSRF and route guards, a template engine (Loom), and an ORM (Mimir) that speaks PostgreSQL over a wire protocol written from scratch.",
				"",
				"# Shape of an app",
				"  app := gh.new(gh.Config{ port = 8091, secret = \"...\" })",
				"  gh.rune(&app, gh.logger)          // middleware",
				"  gh.get(&app, \"/hello/:name\", h)   // a route",
				"  gh.run(&app)                      // listen + serve",
				"",
				"# The pieces",
				"Server (Heimdall), Router, Runes (middleware), Bifrost (the request/response object), Sessions/CSRF/Wards, Mimir (ORM), Loom (templates), Static files, Fetch (outbound HTTP), OpenAPI docs, and a scaffolding CLI.",
				"",
				"Everything is one Odin package (package gjallarhorn) plus the loom subpackage. Each feature keeps its registration verb next to its logic.",
			},
		},
		{
			"App & Config",
			"gh.new, the Config struct, gh.run",
			{
				"# Construct",
				"  app := gh.new(gh.Config{",
				"      port = 8091,          // host \"\" -> loopback; \"0.0.0.0\" exposes",
				"      secret = \"change-me\", // signs session cookies (required in release)",
				"      db_type = .Postgres,  // or .SQLite (opt-in build)",
				"      max_body = 1<<20,     // request-body cap (default 1 MiB)",
				"      workers = 0,          // 0 -> cores*16 clamped [16,256]",
				"  })",
				"",
				"# Run",
				"  gh.run(&app)   // connects DB, migrates models, serves until SIGINT/SIGTERM",
				"",
				"run() refuses to start on an empty or default secret in release builds (warns in -debug). It opens the DB if configured, auto-migrates every remembered model, then serves with a bounded worker pool and graceful drain on shutdown.",
				"",
				"# Notable Config fields",
				"postgres (Postgres_Config), sqlite (file path or :memory:), pool_size, tls_cert / tls_key (HTTPS), docs (OpenAPI docs page).",
			},
		},
		{
			"Router & routes",
			"method verbs, :params, wards, dispatch",
			{
				"# Verbs",
				"  gh.get(&app, \"/things/:id\", get_handler)",
				"  gh.post(&app, \"/things\", create_handler)",
				"  gh.put / gh.patch / gh.delete (+ gh.head, gh.options)",
				"",
				"A handler is a plain proc: proc(b: ^gh.Bifrost). \":name\" segments capture into params; read them with gh.param(b, \"name\") or gh.param_int.",
				"",
				"# Guards (Wards)",
				"  gh.get(&app, \"/account\", handler, gh.require_login)",
				"An optional 4th arg is a Ward: proc(b) -> bool. It runs after the path matches, before the handler; return false to deny (401 fallback).",
				"",
				"# Dispatch order",
				"Exact method+path match first. HEAD with no explicit handler is answered from the matching GET with the body dropped. OPTIONS preflight is short-circuited by the cors rune. Unmatched GET/HEAD falls through to static / Loom mounts, else 404.",
			},
		},
		{
			"Runes (middleware)",
			"gh.rune, next, the onion, built-ins",
			{
				"A rune is middleware: proc(b: ^Bifrost, next: Next). It wraps the rest of the pipeline. Odin has no closures, so the remaining chain is threaded through the Bifrost, not captured.",
				"",
				"# Register (outermost first)",
				"  gh.rune(&app, gh.metrics)",
				"  gh.rune(&app, gh.request_id)",
				"  gh.rune(&app, gh.logger)",
				"  gh.rune(&app, gh.cors)",
				"  gh.rune(&app, gh.rate_limit)",
				"  gh.rune(&app, gh.csrf)",
				"",
				"# Write your own",
				"  my_rune :: proc(b: ^gh.Bifrost, next: gh.Next) {",
				"      // ... before ...",
				"      next(b)          // call the rest of the chain",
				"      // ... after ...  (b.status is now set)",
				"  }",
				"",
				"A rune that writes a response and does NOT call next short-circuits the request. Panics in any rune/handler are recovered (500) without killing the worker.",
			},
		},
		{
			"Bifrost",
			"the request/response object and its helpers",
			{
				"Bifrost carries a request in and a response out. Named so it never shadows Odin's context.",
				"",
				"# Read the request",
				"  gh.param(b, \"id\") / gh.param_int(b, \"id\")   // path params",
				"  gh.query(b, \"q\")                            // query string",
				"  gh.header(b, \"Accept\")                      // request header (case-insensitive)",
				"  b.method, b.path, b.body, b.body_text",
				"",
				"# Write the response",
				"  gh.text(b, 200, \"hello\")",
				"  gh.json(b, 200, value)          // marshals any Odin value",
				"  gh.html(b, 200, \"<h1>hi</h1>\")",
				"  gh.redirect(b, \"/next\")         // 303 by default",
				"  gh.set_header(b, \"X-Foo\", \"bar\") // CR/LF stripped (no header injection)",
				"",
				"# Cookies",
				"  gh.cookie(b, \"name\") / gh.set_cookie(b, \"name\", \"val\", opts)",
			},
		},
		{
			"Request bodies",
			"bind_json, form, multipart uploads",
			{
				"# JSON",
				"  payload: MyType",
				"  if !gh.bind_json(b, &payload) { return } // writes 400 on bad JSON",
				"",
				"# Form (urlencoded or multipart)",
				"  name := gh.form(b)[\"name\"]",
				"Text fields land in form() under either encoding, so CSRF tokens and inputs work the same.",
				"",
				"# File uploads (multipart/form-data)",
				"  if f, ok := gh.upload(b, \"avatar\"); ok {",
				"      // f.filename, f.content_type, f.data ([]u8)",
				"  }",
				"  gh.files(b)   // map[field]Upload of every file part",
				"",
				"File bytes point into the request arena (valid for the request). Sanitize f.filename before using it as a path.",
			},
		},
		{
			"Sessions",
			"signed-cookie sessions, no server state",
			{
				"A session is a small string->string map that rides in a cookie the client holds; the server keeps no state. The cookie carries an HMAC-SHA256 tag (keyed by Config.secret), so a client can't forge or edit it.",
				"",
				"# Use",
				"  gh.session_set(b, \"theme\", \"dark\")",
				"  v, ok := gh.session_get(b, \"theme\")",
				"  gh.session_delete(b, \"theme\")",
				"  gh.session_clear(b)",
				"",
				"# Guarantees",
				"Expiry (default 24h) is signed *inside* the HMAC and enforced server-side, so editing the cookie's Max-Age can't extend it. The cookie is HttpOnly, SameSite=Lax, and Secure over TLS. The tag is verified in constant time; any tamper reads as no session.",
			},
		},
		{
			"CSRF",
			"the csrf rune, synchronizer token",
			{
				"CSRF protection as a rune, using the synchronizer-token pattern: a per-session secret token stored in the signed session. State-changing requests must echo it back.",
				"",
				"# Enable",
				"  gh.rune(&app, gh.csrf)",
				"",
				"Safe methods (GET/HEAD/OPTIONS) pass through and seed a token. Unsafe methods (POST/PUT/PATCH/DELETE) must present it in the X-CSRF-Token header or a csrf_token form field, or get 403.",
				"",
				"# Embed the token",
				"  token := gh.csrf_token(b)   // put in a hidden field or send as the header",
				"",
				"The token is 32 bytes of CSPRNG entropy, compared in constant time. Note: a pure JSON API using bearer tokens (not cookies) usually does not need the csrf rune.",
			},
		},
		{
			"Wards & Auth",
			"login/logout/current_user, require_login",
			{
				"Wards are per-route auth guards (see Router). auth.odin provides session-backed login on top.",
				"",
				"# Log a user in / out",
				"  gh.login(b, user_id)     // records the id in the signed session",
				"  gh.logout(b)             // clears it",
				"  uid, ok := gh.current_user(b)",
				"",
				"# Guard a route",
				"  gh.get(&app, \"/account\", account_handler, gh.require_login)",
				"require_login is a built-in Ward: it admits the request only if a user is logged in, else 401.",
				"",
				"login() assumes you already verified the password — see the Passwords topic for hash_password / verify_password.",
			},
		},
		{
			"Passwords",
			"Argon2id hashing (hash_password / verify_password)",
			{
				"Argon2id (RFC 9106) with OWASP parameters, a fresh 16-byte CSPRNG salt per password, and a constant-time comparison. Output is a standard PHC string you store verbatim.",
				"",
				"# At signup",
				"  stored, ok := gh.hash_password(form[\"password\"])",
				"  // -> $argon2id$v=19$m=19456,t=2,p=1$<salt>$<hash>  (store this)",
				"",
				"# At login",
				"  if gh.verify_password(form[\"password\"], stored) {",
				"      gh.login(b, user_id)",
				"  }",
				"",
				"The cost + salt live in the hash, so old hashes keep verifying after you raise PASSWORD_PARAMS. Hashing is intentionally slow (~19 MiB, a few ms) — pair a login route with the rate_limit rune.",
			},
		},
		{
			"Mimir (ORM)",
			"models, db tags, recall/offer/amend/forget, scan",
			{
				"Mimir maps db:-tagged structs to rows and migrates them at run(). It writes AND reads: scan hydrates rows back into structs.",
				"",
				"# Model",
				"  Sample :: struct {",
				"      id:   int    `db:\"id,pk,auto\"`,",
				"      name: string `db:\"name,notnull\"`,",
				"  }",
				"  gh.remember(&app, Sample)   // auto-migrated at run()",
				"",
				"# Read (query builder)",
				"  w := gh.well(b)",
				"  q := gh.recall(w, Sample)",
				"  gh.whose(&q, \"id = ?\", id)   // ? binds are parameterized",
				"  gh.limit(&q, 1)",
				"  rows, ok := gh.query(w, gh.sql(&q))",
				"  row, found := gh.scan_one(rows, Sample)",
				"",
				"# Write",
				"  gh.offer(w, Sample{name=\"x\"})   // INSERT ... RETURNING id",
				"  gh.amend(w, Sample{id=1,name=\"y\"}) // UPDATE by pk",
				"  gh.forget(w, Sample{id=1})       // DELETE by pk",
				"",
				"# Types",
				"int/float/bool/string, time.Time, uuid, []u8 (bytea), Json (JSONB), and Maybe(T) nullables. Dialect-aware placeholders ($n Postgres, ? SQLite).",
				"",
				"whose-conditions, join and order_by are RAW SQL — never interpolate user input into them; use ? binds.",
			},
		},
		{
			"Loom (templates)",
			"a Jinja dialect, autoescaped, render/warp/list",
			{
				"Loom is the template engine. A template is the warp on the loom; weave runs your data through it as the weft to produce HTML. Output is HTML-escaped by default (XSS-safe) unless a pipeline ends in | safe.",
				"",
				"# Render from a handler",
				"  gh.render(b, \"./templates/page.html\", gh.warp(",
				"      {\"title\", \"Hi\"},",
				"      {\"items\", gh.list(\"a\", \"b\", \"c\")},",
				"  ))",
				"",
				"# Dialect",
				"  {{ expr }}                 output (escaped)   {{ x | upper }}  filters",
				"  {% if c %}..{% elif %}..{% else %}..{% endif %}",
				"  {% for x in xs %}..{% else %}..{% endfor %}   (loop.index/first/last)",
				"  {% extends %} / {% block %} / {% include %} / {% macro %}",
				"",
				"# Mount a directory",
				"  gh.hail(&app, \"/pages\", \"./templates\", provider)",
				"Parsed templates are cached by path+mtime. Filters: upper, lower, trim, capitalize, length, default, join, first, last, escape, safe.",
			},
		},
		{
			"Static files",
			"gh.hail, caching, gzip_static",
			{
				"# Mount",
				"  gh.hail(&app, \"/static\", \"./public\")",
				"A GET-only mount; explicit routes win, mounts are tried when nothing matches. The security checkpoint is path traversal: the resolved path is cleaned and must stay inside the mount root, else 403.",
				"",
				"# Caching",
				"Every file carries an ETag (size+mtime), Last-Modified, and Cache-Control. A still-fresh conditional request (If-None-Match / If-Modified-Since) gets 304 with no body. Tune gh.static_cache_control.",
				"",
				"# Precompressed gzip",
				"If a sibling <file>.gz exists and the client accepts gzip, it's served with Content-Encoding: gzip (compress ahead of time; no on-the-fly compressor).",
			},
		},
		{
			"Fetch (HTTP client)",
			"call other APIs: fetch / fetch_json",
			{
				"A small outbound HTTP(S) client built from the same pieces as the server. Sends Connection: close, reads to EOF, de-chunks a chunked reply.",
				"",
				"# GET",
				"  res, ok := gh.fetch(\"https://api.example.com/things\")",
				"  if ok && res.status == 200 {",
				"      json.unmarshal(res.body_bytes, &payload)",
				"  }",
				"",
				"# With method / headers / body",
				"  gh.fetch(url, gh.Fetch_Request{ method=\"POST\", headers=..., body=... })",
				"  gh.fetch_json(\"POST\", url, payload)   // marshals + sets Content-Type",
				"",
				"ok is false only on a transport failure; a 4xx/5xx is ok=true with the status. Redirects are returned, not followed. https needs a -define:GJ_TLS=true build.",
			},
		},
		{
			"OpenAPI docs",
			"opt-in self-describing API page + openapi.json",
			{
				"Flip one flag and the app serves a Loom-woven docs page plus an openapi.json, generated from the route table at request time — with a live in-browser \"Try it\".",
				"",
				"# Enable",
				"  app := gh.new(gh.Config{ docs = gh.Docs_Config{",
				"      enabled = true, title = \"My API\", version = \"1.0.0\",",
				"  }})",
				"Mounts /api-docs (page) and /api-docs/openapi.json (spec).",
				"",
				"# Describe a route's schema",
				"  gh.describe(&app, .Post, \"/sample\", {request = Sample, response = Sample})",
				"Request/response types are reflected into JSON Schema + example bodies (Maybe(T) -> nullable, structs/slices recurse). Undescribed routes still list; what isn't described is omitted, not invented.",
			},
		},
		{
			"Rate limiting",
			"the rate_limit rune (per-client token bucket)",
			{
				"A per-client token-bucket rune: each client gets rate_limit_burst tokens refilling at rate_limit_rps/sec. Over-limit requests get 429 + Retry-After.",
				"",
				"# Enable + tune",
				"  gh.rate_limit_rps = 10     // sustained rate",
				"  gh.rate_limit_burst = 20   // burst forgiven",
				"  gh.rune(&app, gh.rate_limit)",
				"",
				"The client key is the peer IP captured at accept. Set gh.rate_limit_trust_forwarded = true only behind a trusted proxy that sets X-Forwarded-For (the header is otherwise spoofable). Idle buckets are swept so the table doesn't grow without bound.",
			},
		},
		{
			"Observability",
			"request_id + metrics runes",
			{
				"# request_id",
				"  gh.rune(&app, gh.request_id)",
				"Tags each request with an id (reusing a sane inbound X-Request-Id, else minting one), echoes it in the response header, exposes b.request_id, and the logger prints it — so a log line, the client's response, and an upstream trace line up.",
				"",
				"# metrics (Prometheus)",
				"  gh.rune(&app, gh.metrics)   // register outermost to time the whole chain",
				"Serves a Prometheus text exposition at gh.metrics_path (default /metrics): requests by status class, in-flight gauge, cumulative duration. Counters are atomic; fixed label set (no per-path cardinality).",
				"",
				"# logger",
				"  gh.rune(&app, gh.logger)   // one structured line per request (status, ip, ms, id)",
			},
		},
		{
			"TLS / HTTPS",
			"opt-in OpenSSL at build time",
			{
				"TLS is opt-in at build time — a default build links no OpenSSL and needs none installed.",
				"",
				"  odin run .                       // plaintext, nothing linked",
				"  odin run . -define:GJ_TLS=true   // links libssl: DB TLS + HTTPS + https fetch",
				"",
				"# Serve HTTPS",
				"  app := gh.new(gh.Config{ tls_cert = \"cert.pem\", tls_key = \"key.pem\" })",
				"Both must be set; a TLS build is required or startup fails loudly (never silently falls back to plaintext).",
				"",
				"# DB over TLS",
				"Set Postgres_Config.sslmode (.Prefer / .Require / .Verify_Full). Any mode but .Disable needs a TLS build.",
			},
		},
		{
			"Postgres & SQLite",
			"the data backends Mimir speaks to",
			{
				"# PostgreSQL (default)",
				"A from-scratch PostgreSQL v3 wire-protocol client — no libpq. SCRAM-SHA-256 auth, connection pooling, prepared/parameterized statements.",
				"  postgres = gh.Postgres_Config{ host=..., port=5432, user=..., password=..., dbname=... }",
				"Leave dbname empty to stay offline: migrations print their DDL instead of executing.",
				"",
				"# SQLite (opt-in)",
				"  odin build . -define:GJ_SQLITE=true   // links libsqlite3",
				"  app := gh.new(gh.Config{ db_type = .SQLite, sqlite = \"app.db\" }) // or \":memory:\"",
				"",
				"Mimir generates DDL for Postgres, MySQL and SQLite; Postgres and SQLite have live drivers. Dialect-aware types and placeholders are handled for you.",
			},
		},
		{
			"The CLI",
			"gjallarhorn new / generate / bench / docs",
			{
				"# Scaffold a project",
				"  gjallarhorn new blog        // blog/ with main.odin + vendored gjallarhorn/",
				"  cd blog && odin run .",
				"",
				"# Scaffold a CRUD resource",
				"  gjallarhorn generate resource users   // users/{model,controller,routes}.odin",
				"  // then: users.register(&app) in main()",
				"",
				"# Load-test a running app",
				"  gjallarhorn bench load http://127.0.0.1:8091/ -c 50 -d 5",
				"  gjallarhorn bench hold <url>   // hold connections open",
				"",
				"# These docs",
				"  gjallarhorn docs           // this browser",
				"  gjallarhorn docs loom      // jump to a topic",
				"  gjallarhorn docs --plain   // dump text (for piping)",
			},
		},
	}
	return topics
}
